services:
  survey:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binary_choice_example_container
    hostname: 0.0.0.0
    restart: always
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./database.db:/wd/database.db
      # Images at server instead of online:
      # - /data/images:/wd/assets/images
    networks:
      - survey_network

networks:
  survey_network:
    driver: bridge